// Optional browser check: PLAYWRIGHT_MODULE may point to an existing Playwright installation.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const output = path.resolve('test-results');
fs.mkdirSync(output, { recursive: true });
const profile = fs.mkdtempSync(path.join(output, 'browser-profile-'));
const errors = [];
const options = { channel: 'chrome', headless: true, viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true, locale: 'ja-JP', timezoneId: 'Asia/Tokyo', colorScheme: 'light' };
let context;
async function run() {
  context = await chromium.launchPersistentContext(profile, options);
  let page = context.pages()[0];
  const observe = page => { page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); };
  observe(page);
  const base = process.env.APP_URL || 'http://localhost:4173/meal-log/';
  await page.goto(base);
  await page.getByRole('button', { name: '昼食を追加', exact: true }).waitFor();
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  const scope = new URL('/meal-log/', base).href;
  const registration = await page.evaluate(async () => {
    const worker = await navigator.serviceWorker.ready;
    return { scope: worker.scope, script: worker.active?.scriptURL };
  });
  assert.equal(registration.scope, scope);
  assert.equal(registration.script, new URL('sw.js', scope).href);
  const manifestPath = await page.locator('link[rel=manifest]').getAttribute('href');
  assert.equal(manifestPath, '/meal-log/manifest.webmanifest');
  const manifestResponse = await page.request.get(new URL(manifestPath, base).href);
  assert.equal(manifestResponse.status(), 200);
  const manifest = await manifestResponse.json();
  assert.equal(manifest.start_url, '/meal-log/');
  assert.equal(manifest.scope, '/meal-log/');
  for (const icon of manifest.icons) {
    assert.ok(icon.src.startsWith('/meal-log/icons/'));
    const response = await page.request.get(new URL(icon.src, base).href);
    assert.equal(response.status(), 200);
    assert.match(response.headers()['content-type'], /image\/png/);
  }
  for (const rel of ['icon', 'apple-touch-icon']) {
    const iconPath = await page.locator(`link[rel="${rel}"]`).getAttribute('href');
    assert.ok(iconPath.startsWith('/meal-log/'));
    assert.equal((await page.request.get(new URL(iconPath, base).href)).status(), 200);
  }
  const noticeClose = page.locator('.pwa-notice').getByRole('button', { name: '閉じる' });
  if (await noticeClose.isVisible()) await noticeClose.click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(output, 'home-empty.png'), fullPage: true });

  await page.getByRole('button', { name: '昼食を追加', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: '昼食', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', { name: '食事を保存', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'カロリーを入力してください' }).waitFor();
  await page.getByLabel('食事名', { exact: false }).fill('鶏むね肉とご飯');
  await page.getByRole('spinbutton', { name: /カロリー/ }).fill('-1');
  await page.getByRole('button', { name: '食事を保存', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: '0〜20,000' }).waitFor();
  await page.getByRole('spinbutton', { name: /カロリー/ }).fill('620');
  await page.getByRole('spinbutton', { name: /P たんぱく質/ }).fill('52.2');
  await page.getByRole('spinbutton', { name: /F 脂質/ }).fill('12');
  await page.getByRole('spinbutton', { name: /C 炭水化物/ }).fill('75');
  const originalDate = await page.getByRole('textbox', { name: '日付', exact: true }).count() ? await page.getByRole('textbox', { name: '日付', exact: true }).inputValue() : await page.locator('input[type=date]').inputValue();
  await page.screenshot({ path: path.join(output, 'meal-form.png'), fullPage: true });
  await page.getByRole('button', { name: '食事を保存', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '1,780');
  await page.getByRole('button', { name: '記録', exact: true }).click();
  await page.getByRole('spinbutton', { name: /体重/ }).fill('102.8');
  await page.getByRole('button', { name: '体重を保存', exact: true }).click();
  await page.locator('.weight-card').getByText('102.8', { exact: true }).waitFor();
  await page.reload();
  await page.locator('.weight-card').getByText('102.8', { exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '1,780');
  await page.screenshot({ path: path.join(output, 'home-populated.png'), fullPage: true });

  await page.getByRole('button', { name: '設定', exact: true }).click();
  await page.getByRole('spinbutton', { name: /カロリー/ }).fill('2300');
  await page.getByLabel('目標体重（任意）', { exact: false }).fill('90');
  await page.getByRole('button', { name: '目標を保存' }).click();
  await page.getByRole('status').filter({ hasText: '目標を保存しました' }).waitFor();
  await page.getByRole('switch', { name: 'PFCの小数表示' }).click();
  await page.waitForFunction(() => document.querySelector('[role=switch]')?.getAttribute('aria-checked') === 'false');
  await page.getByRole('button', { name: 'ダーク', exact: true }).click();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
  await page.screenshot({ path: path.join(output, 'settings-dark.png'), fullPage: true });
  await page.getByRole('button', { name: 'ホーム', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '1,680');
  assert.equal(await page.locator('.protein .pfc-value b').textContent(), '52');
  await page.screenshot({ path: path.join(output, 'home-dark.png'), fullPage: true });

  await page.getByRole('button', { name: '履歴', exact: true }).click();
  await page.locator('.history-row').click();
  await page.getByRole('button', { name: '編集する' }).click();
  assert.equal(await page.getByRole('spinbutton', { name: /P たんぱく質/ }).inputValue(), '52.2');
  await page.getByRole('spinbutton', { name: /カロリー/ }).fill('2600');
  await page.getByRole('button', { name: '変更を保存' }).click();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '300');
  assert.match(await page.locator('.calorie-hero').textContent(), /オーバー/);
  await page.getByRole('button', { name: '履歴', exact: true }).click();
  await page.locator('.history-row').click();
  await page.getByRole('button', { name: '編集する' }).click();
  const priorDate = new Date(`${originalDate}T12:00:00+09:00`);
  priorDate.setUTCDate(priorDate.getUTCDate() - 1);
  const movedDate = priorDate.toISOString().slice(0, 10);
  await page.locator('input[type=date]').fill(movedDate);
  await page.getByRole('button', { name: '変更を保存' }).click();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '300');
  await page.getByRole('button', { name: '今日', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '2,300');
  await page.getByRole('button', { name: '履歴', exact: true }).click();
  await page.locator('.history-row').click();
  await page.getByRole('button', { name: 'この食事を削除' }).click();
  await page.getByRole('button', { name: 'キャンセル', exact: true }).click();
  await page.getByRole('button', { name: 'この食事を削除' }).click();
  await page.getByRole('button', { name: '削除する', exact: true }).click();
  await page.getByRole('heading', { name: 'まだ食事の記録がありません' }).waitFor();
  await page.getByRole('button', { name: '分析', exact: true }).click();
  assert.equal(await page.locator('.analysis-summary strong').textContent(), '0');

  await context.close();
  context = await chromium.launchPersistentContext(profile, options);
  await context.setOffline(true);
  page = context.pages()[0]; observe(page);
  await page.goto(base);
  await page.locator('.weight-card').getByText('102.8', { exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '2,300');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.getByRole('button', { name: '朝食を追加', exact: true }).click();
  await page.getByLabel('食事名', { exact: false }).fill('オフラインで登録');
  await page.getByRole('spinbutton', { name: /カロリー/ }).fill('100');
  await page.getByRole('button', { name: '食事を保存', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '2,200');
  await page.reload();
  await page.waitForFunction(() => document.querySelector('.calorie-hero strong')?.textContent === '2,200');
  await page.setViewportSize({ width: 320, height: 740 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: '食事を追加', exact: true }).first().click();
  assert.equal(await page.locator('dialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth), true);
  assert.deepEqual(errors, []);
  const report = { result: 'PASS', browser: 'Chrome, iPhone 14 viewport (390×844)', checks: ['empty state and layout', 'preselected meal category', 'required/negative validation', 'meal and weight persistence after reload', 'targets/theme/decimal settings', 'unrounded stored PFC', 'edit and calorie excess', 'move meal to another day', 'confirmed deletion and cancel', 'today analysis', 'browser restart and offline cold start', 'offline create/reload', '320px layout', 'no console or page errors'], physicalSafariTested: false };
  fs.writeFileSync(path.join(output, 'browser-report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
}
run().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { if (context) await context.close(); });
